apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-odoo
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-odoo
  template:
    metadata:
      labels:
        app: cloudflared-odoo
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - --protocol
        - http2
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-odoo-token
              key: TUNNEL_TOKEN
