alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: worker
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  nodeSelector:
    kubernetes.io/hostname: worker
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 640Mi
  persistence:
    enabled: true
    storageClassName: local-path
    size: 1Gi
  env:
    GF_PLUGINS_PREINSTALL_DISABLED: "true"
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 10
    periodSeconds: 15
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
    periodSeconds: 15

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
